// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Podcast struct {
	Date string `json:"date"`
	URL  string `json:"url"`
}

type Preferences struct {
	Country string `json:"country"`
	Topic   string `json:"topic"`
}

type Query struct {
}

type User struct {
	ID           string       `json:"id"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"PasswordHash"`
	Preferences  *Preferences `json:"preferences,omitempty"`
}
